name: requests
version: 0.0.1
description: Requests
author: yamal lng
homepage: http://yamallng.ru/

# Pubspec Format:
# https://www.dartlang.org/tools/pub/pubspec
#
# Repository of packages of software for the Dart programming language:
# https://pub.dartlang.org/

dependencies:
    angular2: ^3.0.0                      # Dart implementation of the Angular web framework. https://pub.dartlang.org/packages/angular2
    browser: ^0.10.0                      # The bootstrap dart.js script for Dart apps running in the browser. https://pub.dartlang.org/packages/browser
    dart_to_js_script_rewriter: ^1.0.2    # Replaces Dart script tags with JavaScript script tags. https://pub.dartlang.org/packages/dart_to_js_script_rewriter
    http: ^0.11.3                         # A composable, Future-based API for making HTTP requests. https://pub.dartlang.org/packages/http
    intl: any
    json_object: any
    reflectable: ^1.0.2                   # Allows programmers to reduce certain usages of dynamic reflection to a transformer generated specialization with the same behavior. https://pub.dartlang.org/packages/reflectable
    uuid: any
    auth:
      git: http://cm-ylng-msk-04/git/auth.frontend.git
    grid:
      git: http://cm-ylng-msk-04/git/grid.frontend.git
    auth_router_outlet:
      git: http://cm-ylng-msk-04/git/auth_router_outlet.frontend.git
    daterangepicker:
      git: http://cm-ylng-msk-04/git/daterangepicker.frontend.git
    alert:
      git: http://cm-ylng-msk-04/git/alert.frontend.git      
    logger:
      git: http://cm-ylng-msk-04/git/logger.frontend.git
    config:
      git: http://cm-ylng-msk-04/git/config.frontend.git
    angular_utils:
      git: http://cm-ylng-msk-04/git/angular_utils.frontend.git
    aside:
      git: http://cm-ylng-msk-04/git/aside.frontend.git
    converters:
      git: http://cm-ylng-msk-04/git/converters.frontend.git
    time_sheet:
      git: http://cm-ylng-msk-04/git/time_sheet.frontend.git
    http_wrapper:
      git: http://cm-ylng-msk-04/git/http_wrapper.frontend.git
dev_dependencies:
    test: ^0.12.18                        # A library for writing dart unit tests. https://pub.dartlang.org/packages/test
    yaml: ^2.1.12                         # A parser for YAML. https://pub.dartlang.org/packages/yaml
    master_layout:
      git: http://cm-ylng-msk-04/git/master_layout.frontend.git

# Used to configure dart2js or other transformers
transformers:
    - angular2:
        platform_directives:
          - package:angular2/common.dart#COMMON_DIRECTIVES
        platform_pipes:
          - package:angular2/common.dart#COMMON_PIPES
        entry_points: web/main.dart
        resolved_identifiers:
            BrowserClient: 'package:http/browser_client.dart'
            Client: 'package:http/http.dart'
    - reflectable:
         entry_points:
           - web/main.dart # The path to your main file
         formatted: true # Optional.
    - dart_to_js_script_rewriter
    - $dart2js:
        commandLineOptions:
            - --trust-type-annotations
            - --trust-primitives
            - --show-package-warnings # Show warnings and hints generated from packages.